

apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthin-github
  labels:
    app: healthin-server
spec:
  selector:
    matchLabels:
      app: healthin-server
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: healthin-server
    spec:
      containers:
        - name: healthin-server
          image: 876456430036.dkr.ecr.ap-northeast-2.amazonaws.com/healthin-server:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
