apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: healthin-api-ingress
  namespace: healthin
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - api.be-healthy.life
      secretName: api-be-healthy-life-tls
  rules:
    - host: api.be-healthy.life
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: healthin-api
                port:
                  number: 3000
