name: Run Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: healthin_test
          POSTGRES_USER: healthin_server
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Run tests
        env:
          APP_SECRET: secret
        run: yarn test --coverage=reports

      - uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: reports/clover.xml
